# Collocation

In [1]:
import polars as pl
import polars.selectors as cs
import polars_corpus as plc
import math

In [2]:
bnc = pl.read_parquet("bnc.parquet")

In [3]:
m = plc.search(bnc, '[token="dangerous"]')

In [4]:
collocs = m.collocates("token", window=3).sort(by="f12", descending=True)
collocs

shape: (5_134, 6)
┌───────────┬───────────┬──────┬───────┬─────────┬───────────┐
│ collocate ┆ e12       ┆ f12  ┆ f1    ┆ f2      ┆ n         │
│ ---       ┆ ---       ┆ ---  ┆ ---   ┆ ---     ┆ ---       │
│ str       ┆ f64       ┆ u32  ┆ u32   ┆ u32     ┆ i32       │
╞═══════════╪═══════════╪══════╪═══════╪═════════╪═══════════╡
│ .         ┆ 27.716702 ┆ 1760 ┆ 32542 ┆ 4715138 ┆ 112429158 │
│ ,         ┆ 0.500863  ┆ 1501 ┆ 32542 ┆ 5017057 ┆ 112429158 │
│ and       ┆ 37.740954 ┆ 1230 ┆ 32542 ┆ 2506072 ┆ 112429158 │
│ a         ┆ 16.48063  ┆ 1115 ┆ 32542 ┆ 2036673 ┆ 112429158 │
│ the       ┆ 36.572722 ┆ 1088 ┆ 32542 ┆ 5405646 ┆ 112429158 │
│ …         ┆ …         ┆ …    ┆ …     ┆ …       ┆ …         │
│ gardens   ┆ 0.730268  ┆ 1    ┆ 32542 ┆ 2523    ┆ 112429158 │
│ 1986      ┆ 2.279086  ┆ 1    ┆ 32542 ┆ 7874    ┆ 112429158 │
│ 52        ┆ 0.298996  ┆ 1    ┆ 32542 ┆ 1033    ┆ 112429158 │
│ director  ┆ 2.4542    ┆ 1    ┆ 32542 ┆ 8479    ┆ 112429158 │
│ McMinn    ┆ 0.003184  ┆ 1    ┆ 32542 ┆ 11      ┆ 112429158 │
└───────────┴───────────┴──────┴───────┴─────────┴───────────┘

In [5]:
ll = collocs.with_columns(LL=plc.loglik("f12", "f1", "f2", "n")).sort(by="LL", descending=True)
ll

shape: (5_134, 7)
┌───────────────┬───────────┬─────┬───────┬────────┬───────────┬─────────────┐
│ collocate     ┆ e12       ┆ f12 ┆ f1    ┆ f2     ┆ n         ┆ LL          │
│ ---           ┆ ---       ┆ --- ┆ ---   ┆ ---    ┆ ---       ┆ ---         │
│ str           ┆ f64       ┆ u32 ┆ u32   ┆ u32    ┆ i32       ┆ f64         │
╞═══════════════╪═══════════╪═════╪═══════╪════════╪═══════════╪═════════════╡
│ potentially   ┆ 0.686852  ┆ 154 ┆ 32542 ┆ 2373   ┆ 112429158 ┆ 1371.303522 │
│ most          ┆ 25.381387 ┆ 261 ┆ 32542 ┆ 87690  ┆ 112429158 ┆ 747.631811  │
│ very          ┆ 33.285248 ┆ 285 ┆ 32542 ┆ 114997 ┆ 112429158 ┆ 723.08036   │
│ be            ┆ 34.557613 ┆ 616 ┆ 32542 ┆ 647322 ┆ 112429158 ┆ 615.037104  │
│ is            ┆ 13.869906 ┆ 757 ┆ 32542 ┆ 971795 ┆ 112429158 ┆ 554.721497  │
│ …             ┆ …         ┆ …   ┆ …     ┆ …      ┆ …         ┆ …           │
│ agencies      ┆ 1.004372  ┆ 1   ┆ 32542 ┆ 3470   ┆ 112429158 ┆ 0.000019    │
│ Defence       ┆ 0.996847  ┆ 1   ┆ 32542 ┆ 3444   ┆ 112429158 ┆ 0.00001     │
│ officer       ┆ 2.004114  ┆ 2   ┆ 32542 ┆ 6924   ┆ 112429158 ┆ 0.000008    │
│ wages         ┆ 0.997715  ┆ 1   ┆ 32542 ┆ 3447   ┆ 112429158 ┆ 0.000005    │
│ Middlesbrough ┆ 0.998005  ┆ 1   ┆ 32542 ┆ 3448   ┆ 112429158 ┆ 0.000004    │
└───────────────┴───────────┴─────┴───────┴────────┴───────────┴─────────────┘

In [6]:
# a = frequency of node-collocate pairs
a = 154
# b = frequency of node without collocate
b = 32542-a
# c = frequency of collocate without node
c = 2373-a

# d = words in corpus - occurrences of node and collocate
N = 112429158
d = N - a - b - c

LL2 = 2*(
          a*math.log(a)
         +b*math.log(b)
         +c*math.log(c)
         +d*math.log(d)
         -(a+b)*math.log(a+b)
         -(a+c)*math.log(a+c)
         -(b+d)*math.log(b+d)
         -(c+d)*math.log(c+d)
         +(N)*math.log(N))
LL2

1371.303521156311