# Concordances

In [1]:
import sys

if ".." not in sys.path:
    sys.path.append("..")

import polars as pl
import polars.selectors as cs
import polars_corpus as plc

In [2]:
c = pl.read_parquet("bnc.parquet")  # .head(5000000)

In [25]:
r = plc.search(c, '([c5="AJ.*"] | [c5="NN.*"])+ [c5="NN.*"]')
r

SearchResults<'([c5="AJ.*"] | [c5="NN.*"])+ [c5="NN.*"]'; 6,236,829 matches>

In [26]:
r.matches(['token','c5', 'mode'])

shape: (6_236_829, 3)
┌─────────────────────────────────┬─────────────────────────────┬─────────────────────────────────┐
│ token_node                      ┆ c5_node                     ┆ mode_node                       │
│ ---                             ┆ ---                         ┆ ---                             │
│ list[str]                       ┆ list[str]                   ┆ list[cat]                       │
╞═════════════════════════════════╪═════════════════════════════╪═════════════════════════════════╡
│ ["Immune", "Deficiency", "Synd… ┆ ["AJ0", "NN1", "NN1"]       ┆ ["written", "written", "writte… │
│ ["Human", "Immuno", … "Virus"]  ┆ ["AJ0-NN1", "NN1", … "NN1"] ┆ ["written", "written", … "writ… │
│ ["defence", "system"]           ┆ ["NN1", "NN1"]              ┆ ["written", "written"]          │
│ ["unprotected", "sexual", "int… ┆ ["AJ0", "AJ0", "NN1"]       ┆ ["written", "written", "writte… │
│ ["infected", "partner"]         ┆ ["AJ0", "NN1"]              ┆ ["written", "written"]          │
│ …                               ┆ …                           ┆ …                               │
│ ["milk", "shake"]               ┆ ["NN1", "NN1-VVB"]          ┆ ["spoken", "spoken"]            │
│ ["little", "ones"]              ┆ ["AJ0", "NN2"]              ┆ ["spoken", "spoken"]            │
│ ["back", "seat"]                ┆ ["NN1", "NN1"]              ┆ ["spoken", "spoken"]            │
│ ["nice", "clothes"]             ┆ ["AJ0", "NN2"]              ┆ ["spoken", "spoken"]            │
│ ["nice", "clothes"]             ┆ ["AJ0", "NN2"]              ┆ ["spoken", "spoken"]            │
└─────────────────────────────────┴─────────────────────────────┴─────────────────────────────────┘

In [27]:
r.matches(pl.col('token').str.to_lowercase()).group_by('token_node').len().sort(by='len', descending=True)

shape: (2_526_015, 2)
┌─────────────────────────────────┬──────┐
│ token_node                      ┆ len  │
│ ---                             ┆ ---  │
│ list[str]                       ┆ u32  │
╞═════════════════════════════════╪══════╡
│ ["prime", "minister"]           ┆ 7297 │
│ ["other", "hand"]               ┆ 5486 │
│ ["long", "time"]                ┆ 4097 │
│ ["other", "people"]             ┆ 4018 │
│ ["great", "deal"]               ┆ 4017 │
│ …                               ┆ …    │
│ ["neutral", "sky"]              ┆ 1    │
│ ["working", "trades"]           ┆ 1    │
│ ["similar", "tax-accounting", … ┆ 1    │
│ ["double", "liposome", "body"]  ┆ 1    │
│ ["cheap", "imported", "imitati… ┆ 1    │
└─────────────────────────────────┴──────┘

In [28]:
r = plc.search(c, '[token="[Mm]ale"] [token="[Ss]peaker"]')
r.kwic_concordance('token', 5)

shape: (3_065, 3)
┌─────────────────────────────────┬─────────────────────┬─────────────────────────────────┐
│ token_left_context              ┆ token_node          ┆ token_right_context             │
│ ---                             ┆ ---                 ┆ ---                             │
│ list[str]                       ┆ list[str]           ┆ list[str]                       │
╞═════════════════════════════════╪═════════════════════╪═════════════════════════════════╡
│ [",", "addressed", … "intimate… ┆ ["male", "speaker"] ┆ [""", "(", … "1971"]            │
│ ["in", "the", … "."]            ┆ ["Male", "speaker"] ┆ ["Indulgent", "parents", … "ch… │
│ ["'re", "threatening", … "."]   ┆ ["Male", "speaker"] ┆ ["They", "threaten", … "Voice"… │
│ ["indiscriminate", "buying", …… ┆ ["Male", "speaker"] ┆ ["Pet", "shops", … "importing"… │
│ ["the", "vehicles", … ":"]      ┆ ["Male", "speaker"] ┆ ["He", "looked", … "the"]       │
│ …                               ┆ …                   ┆ …                               │
│ [",", "loads", … "."]           ┆ ["Male", "speaker"] ┆ ["You", "'ve", … "total"]       │
│ ["hell", "of", … "."]           ┆ ["Male", "speaker"] ┆ ["It", "'s", … "'s"]            │
│ ["of", "all", … "."]            ┆ ["Male", "speaker"] ┆ ["It", "'s", … ","]             │
│ [";", "loads", … "."]           ┆ ["Male", "speaker"] ┆ ["You", "'ve", … "total"]       │
│ ["hell", "of", … "."]           ┆ ["Male", "speaker"] ┆ ["It", "'s", … "'s"]            │
└─────────────────────────────────┴─────────────────────┴─────────────────────────────────┘

In [29]:
r = plc.search(c.filter(mode="spoken"), '[c5="AJ.*"]+ [c5="NN.*"]+')
r.matches(pl.col('token').str.to_lowercase()).group_by('token_node').len().sort(by='len', descending=True)

shape: (103_647, 2)
┌─────────────────────────────────┬──────┐
│ token_node                      ┆ len  │
│ ---                             ┆ ---  │
│ list[str]                       ┆ u32  │
╞═════════════════════════════════╪══════╡
│ ["little", "bit"]               ┆ 1744 │
│ ["other", "people"]             ┆ 823  │
│ ["long", "time"]                ┆ 764  │
│ ["other", "day"]                ┆ 645  │
│ ["other", "side"]               ┆ 591  │
│ …                               ┆ …    │
│ ["sophisticated", "apparatus"]  ┆ 1    │
│ ["different", "little", "works… ┆ 1    │
│ ["overwhelming", "support"]     ┆ 1    │
│ ["barbarous", "dissonance"]     ┆ 1    │
│ ["profound", "admiration"]      ┆ 1    │
└─────────────────────────────────┴──────┘

In [30]:
r = plc.search(c, '[token="new"] [token="settlement"]')
r.kwic_concordance('token', 5)

shape: (642, 3)
┌────────────────────────────────┬───────────────────────┬─────────────────────────────────┐
│ token_left_context             ┆ token_node            ┆ token_right_context             │
│ ---                            ┆ ---                   ┆ ---                             │
│ list[str]                      ┆ list[str]             ┆ list[str]                       │
╞════════════════════════════════╪═══════════════════════╪═════════════════════════════════╡
│ ["to", "go", … "A"]            ┆ ["new", "settlement"] ┆ ["is", "going", … "needed"]     │
│ ["decision", "in", … "a"]      ┆ ["new", "settlement"] ┆ ["will", "relieve", … "elsewhe… │
│ ["Foxley", "Wood", … "‘"]      ┆ ["new", "settlement"] ┆ ["’", "on", … "of"]             │
│ ["developing", "the", … "the"] ┆ ["new", "settlement"] ┆ ["system", ".", … "intends"]    │
│ ["bike", "to", … "'s"]         ┆ ["new", "settlement"] ┆ [".", "It", … "incidentally"]   │
│ …                              ┆ …                     ┆ …                               │
│ ["area", "of", … "the"]        ┆ ["new", "settlement"] ┆ ["to", "that", … "areas"]       │
│ ["'s", "criterion", … "the"]   ┆ ["new", "settlement"] ┆ ["should", "be", … "miles"]     │
│ ["to", "the", … "a"]           ┆ ["new", "settlement"] ┆ ["in", "Selby", … "main"]       │
│ [",", "but", … "the"]          ┆ ["new", "settlement"] ┆ ["to", "cover", … "in"]         │
│ ["he", "added", … "agree"]     ┆ ["new", "settlement"] ┆ ["system", "By", … "A"]         │
└────────────────────────────────┴───────────────────────┴─────────────────────────────────┘