In [2]:
import polars as pl
import polars_corpus as plc

In [6]:
c = pl.read_parquet('bnc.parquet') #.head(5000000)

In [7]:
r = plc.search(c, '[c5="AJ.*"]+ [c5="NN.*"]')
r

SearchResults<'[c5="AJ.*"]+ [c5="NN.*"]', 4,693,612 matches>

In [8]:
r.matches().group_by('token').len().sort(by='len', descending=True)

shape: (1_830_196, 2)
┌─────────────────────────────────┬──────┐
│ token                           ┆ len  │
│ ---                             ┆ ---  │
│ list[str]                       ┆ u32  │
╞═════════════════════════════════╪══════╡
│ ["Prime", "Minister"]           ┆ 7289 │
│ ["other", "hand"]               ┆ 5551 │
│ ["long", "time"]                ┆ 4169 │
│ ["great", "deal"]               ┆ 4019 │
│ ["other", "people"]             ┆ 3888 │
│ …                               ┆ …    │
│ ["SOED", "booklet"]             ┆ 1    │
│ ["light-fingered", "whirl"]     ┆ 1    │
│ ["dark", "red", "roses"]        ┆ 1    │
│ ["cross", "pieces"]             ┆ 1    │
│ ["long-standing", "permission"… ┆ 1    │
└─────────────────────────────────┴──────┘

In [9]:
r = plc.search(c, '[pos="SUBST"]{3,}')

In [10]:
r.matches() \
    .with_columns(pl.col('token').list.join(' ')) \
    .group_by('token') \
    .len() \
    .sort(by='len', descending=True)

shape: (377_445, 2)
┌─────────────────────────────────┬──────┐
│ token                           ┆ len  │
│ ---                             ┆ ---  │
│ str                             ┆ u32  │
╞═════════════════════════════════╪══════╡
│ Pounds Date Award               ┆ 1811 │
│ Award Ref No                    ┆ 797  │
│ Research grant Award Ref No     ┆ 508  │
│ UN Security Council             ┆ 301  │
│ trade union movement            ┆ 223  │
│ …                               ┆ …    │
│ investment company director hu… ┆ 1    │
│ Mandarin Club guest             ┆ 1    │
│ RSFSR press minister Mikhail P… ┆ 1    │
│ government housing policies     ┆ 1    │
│ Pupil GEOFF LACEY               ┆ 1    │
└─────────────────────────────────┴──────┘