In [76]:
import polars as pl
import polars.selectors as cs
import polars_corpus as plc

In [2]:
c = pl.read_parquet('bnc.parquet') #.head(5000000)

In [15]:
r = plc.search(c, '[c5="AJ.*"]+ [c5="NN.*"]')
r

SearchResults<'[c5="AJ.*"]+ [c5="NN.*"]', 4,693,612 matches>

In [16]:
r.matches()

shape: (4_693_612, 8)
┌────────────┬────────────┬────────────┬─────────┬────────────┬───────────┬───────────┬────────────┐
│ token      ┆ c5         ┆ pos        ┆ mode    ┆ text_type  ┆ fileid    ┆ sent_tag  ┆ hw         │
│ ---        ┆ ---        ┆ ---        ┆ ---     ┆ ---        ┆ ---       ┆ ---       ┆ ---        │
│ list[str]  ┆ list[str]  ┆ list[str]  ┆ cat     ┆ list[cat]  ┆ list[cat] ┆ list[str] ┆ list[str]  │
╞════════════╪════════════╪════════════╪═════════╪════════════╪═══════════╪═══════════╪════════════╡
│ ["immigran ┆ ["AJ0-NN1" ┆ ["ADJ",    ┆ written ┆ ["NONAC"]  ┆ ["H0C"]   ┆ ["I"]     ┆ ["immigran │
│ t",        ┆ , "NN1"]   ┆ "SUBST"]   ┆         ┆            ┆           ┆           ┆ t",        │
│ "runner"]  ┆            ┆            ┆         ┆            ┆           ┆           ┆ "runner"]  │
│ ["Select", ┆ ["AJ0",    ┆ ["ADJ",    ┆ written ┆ ["OTHERPUB ┆ ["HHX"]   ┆ ["I"]     ┆ ["select", │
│ "Committee ┆ "NN1"]     ┆ "SUBST"]   ┆         ┆ "]         ┆           ┆           ┆ "committee │
│ "]         ┆            ┆            ┆         ┆            ┆           ┆           ┆ "]         │
│ ["natural" ┆ ["AJ0",    ┆ ["ADJ",    ┆ written ┆ ["NONAC"]  ┆ ["BN4"]   ┆ ["I"]     ┆ ["natural" │
│ , "instinc ┆ "NN1"]     ┆ "SUBST"]   ┆         ┆            ┆           ┆           ┆ , "instinc │
│ t"]        ┆            ┆            ┆         ┆            ┆           ┆           ┆ t"]        │
│ ["multiple ┆ ["AJ0-NN1" ┆ ["ADJ",    ┆ written ┆ ["OTHERPUB ┆ ["CAD"]   ┆ ["I"]     ┆ ["multiple │
│ ", "Austra ┆ , "AJ0",   ┆ "SUBST"]   ┆         ┆ "]         ┆           ┆           ┆ ", "austra │
│ lian",     ┆ "NN1"]     ┆            ┆         ┆            ┆           ┆           ┆ lian",     │
│ "Os…       ┆            ┆            ┆         ┆            ┆           ┆           ┆ "os…       │
│ ["frustrat ┆ ["AJ0",    ┆ ["ADJ",    ┆ written ┆ ["NEWS"]   ┆ ["CEP"]   ┆ ["I"]     ┆ ["frustrat │
│ ed",       ┆ "NN1"]     ┆ "SUBST"]   ┆         ┆            ┆           ┆           ┆ ed",       │
│ "punch"]   ┆            ┆            ┆         ┆            ┆           ┆           ┆ "punch"]   │
│ …          ┆ …          ┆ …          ┆ …       ┆ …          ┆ …         ┆ …         ┆ …          │
│ ["Haliaeet ┆ ["AJ0",    ┆ ["ADJ",    ┆ written ┆ ["OTHERPUB ┆ ["B31"]   ┆ ["I"]     ┆ ["haliaeet │
│ us", "albi ┆ "NN1"]     ┆ "SUBST"]   ┆         ┆ "]         ┆           ┆           ┆ us", "albi │
│ cilla"]    ┆            ┆            ┆         ┆            ┆           ┆           ┆ cilla"]    │
│ ["shallow" ┆ ["AJ0",    ┆ ["ADJ",    ┆ written ┆ ["NONAC"]  ┆ ["ASR"]   ┆ ["I"]     ┆ ["shallow" │
│ , "lakes"] ┆ "NN2"]     ┆ "SUBST"]   ┆         ┆            ┆           ┆           ┆ , "lake"]  │
│ ["other",  ┆ ["AJ0",    ┆ ["ADJ",    ┆ written ┆ ["NONAC"]  ┆ ["CDF"]   ┆ ["I"]     ┆ ["other",  │
│ "words"]   ┆ "NN2"]     ┆ "SUBST"]   ┆         ┆            ┆           ┆           ┆ "word"]    │
│ ["big",    ┆ ["AJ0",    ┆ ["ADJ",    ┆ written ┆ ["FICTION" ┆ ["FYY"]   ┆ ["I"]     ┆ ["big",    │
│ "fun"]     ┆ "NN1"]     ┆ "SUBST"]   ┆         ┆ ]          ┆           ┆           ┆ "fun"]     │
│ ["starving ┆ ["AJ0",    ┆ ["ADJ",    ┆ written ┆ ["OTHERPUB ┆ ["EF5"]   ┆ ["I"]     ┆ ["starving │
│ ", "kids"] ┆ "NN2"]     ┆ "SUBST"]   ┆         ┆ "]         ┆           ┆           ┆ ", "kid"]  │
└────────────┴────────────┴────────────┴─────────┴────────────┴───────────┴───────────┴────────────┘

In [71]:
r.matches().group_by('fileid','text_type').len()

shape: (3_985, 3)
┌───────────┬─────────────┬─────┐
│ fileid    ┆ text_type   ┆ len │
│ ---       ┆ ---         ┆ --- │
│ list[cat] ┆ list[cat]   ┆ u32 │
╞═══════════╪═════════════╪═════╡
│ ["HMA"]   ┆ ["OTHERSP"] ┆ 167 │
│ ["EE2"]   ┆ ["ACPROSE"] ┆ 57  │
│ ["J8K"]   ┆ ["OTHERSP"] ┆ 36  │
│ ["HP0"]   ┆ ["FICTION"] ┆ 44  │
│ ["A5W"]   ┆ ["NEWS"]    ┆ 22  │
│ …         ┆ …           ┆ …   │
│ ["K3D"]   ┆ ["NEWS"]    ┆ 9   │
│ ["JJP"]   ┆ ["OTHERSP"] ┆ 21  │
│ ["CBY"]   ┆ ["NONAC"]   ┆ 736 │
│ ["AND"]   ┆ ["NONAC"]   ┆ 122 │
│ ["AKC"]   ┆ ["NEWS"]    ┆ 4   │
└───────────┴─────────────┴─────┘

In [20]:
r.matches().filter(pl.col('sent_tag')==["I","B"])

shape: (2_378, 8)
┌────────────┬────────────┬────────────┬─────────┬────────────┬───────────┬────────────┬───────────┐
│ token      ┆ c5         ┆ pos        ┆ mode    ┆ text_type  ┆ fileid    ┆ sent_tag   ┆ hw        │
│ ---        ┆ ---        ┆ ---        ┆ ---     ┆ ---        ┆ ---       ┆ ---        ┆ ---       │
│ list[str]  ┆ list[str]  ┆ list[str]  ┆ cat     ┆ list[cat]  ┆ list[cat] ┆ list[str]  ┆ list[str] │
╞════════════╪════════════╪════════════╪═════════╪════════════╪═══════════╪════════════╪═══════════╡
│ ["odd",    ┆ ["AJ0",    ┆ ["ADJ",    ┆ spoken  ┆ ["CONVRSN" ┆ ["KR0"]   ┆ ["I", "B"] ┆ ["odd",   │
│ "bloody",  ┆ "NN1"]     ┆ "SUBST"]   ┆         ┆ ]          ┆           ┆            ┆ "bloody", │
│ "hell"]    ┆            ┆            ┆         ┆            ┆           ┆            ┆ "hell"]   │
│ ["wet",    ┆ ["AJ0",    ┆ ["ADJ",    ┆ spoken  ┆ ["CONVRSN" ┆ ["KE1"]   ┆ ["I", "B"] ┆ ["wet",   │
│ "Finer",   ┆ "AJC",     ┆ "SUBST"]   ┆         ┆ ]          ┆           ┆            ┆ "fine",   │
│ "points"]  ┆ "NN2"]     ┆            ┆         ┆            ┆           ┆            ┆ "point"]  │
│ ["INTERNAT ┆ ["AJ0",    ┆ ["ADJ",    ┆ written ┆ ["OTHERPUB ┆ ["A7G"]   ┆ ["I", "B"] ┆ ["interna │
│ IONAL",    ┆ "NN1"]     ┆ "SUBST"]   ┆         ┆ "]         ┆           ┆            ┆ tional",  │
│ "NATIONAL" ┆            ┆            ┆         ┆            ┆           ┆            ┆ "national │
│ , …        ┆            ┆            ┆         ┆            ┆           ┆            ┆ ", …      │
│ ["keen",   ┆ ["AJ0",    ┆ ["ADJ",    ┆ written ┆ ["FICTION" ┆ ["H9T"]   ┆ ["I", "B"] ┆ ["keen",  │
│ "apex"]    ┆ "NN1"]     ┆ "SUBST"]   ┆         ┆ ]          ┆           ┆            ┆ "apex"]   │
│ ["personal ┆ ["AJ0",    ┆ ["ADJ",    ┆ written ┆ ["NEWS"]   ┆ ["CH1"]   ┆ ["I", "B"] ┆ ["persona │
│ ",         ┆ "NN1"]     ┆ "SUBST"]   ┆         ┆            ┆           ┆            ┆ l", "scan │
│ "SCANDAL"] ┆            ┆            ┆         ┆            ┆           ┆            ┆ dal"]     │
│ …          ┆ …          ┆ …          ┆ …       ┆ …          ┆ …         ┆ …          ┆ …         │
│ ["Noisy",  ┆ ["AJ0",    ┆ ["ADJ",    ┆ written ┆ ["NEWS"]   ┆ ["K2H"]   ┆ ["I", "B"] ┆ ["noisy", │
│ "Duran"]   ┆ "NN1-NP0"] ┆ "SUBST"]   ┆         ┆            ┆           ┆            ┆ "duran"]  │
│ ["misguide ┆ ["AJ0",    ┆ ["ADJ",    ┆ written ┆ ["NONAC"]  ┆ ["B7J"]   ┆ ["I", "B"] ┆ ["misguid │
│ d", "RIGHT ┆ "NN0"]     ┆ "SUBST"]   ┆         ┆            ┆           ┆            ┆ ed", "rig │
│ -THINKING" ┆            ┆            ┆         ┆            ┆           ┆            ┆ ht-thinki │
│ …          ┆            ┆            ┆         ┆            ┆           ┆            ┆ ng"…      │
│ ["Little", ┆ ["AJ0",    ┆ ["ADJ",    ┆ written ┆ ["ACPROSE" ┆ ["HJ0"]   ┆ ["I", "B"] ┆ ["little" │
│ "Departmen ┆ "NN1"]     ┆ "SUBST"]   ┆         ┆ ]          ┆           ┆            ┆ , "depart │
│ t"]        ┆            ┆            ┆         ┆            ┆           ┆            ┆ ment"]    │
│ ["SPECIAL" ┆ ["AJ0",    ┆ ["ADJ",    ┆ written ┆ ["OTHERPUB ┆ ["CGV"]   ┆ ["I", "B"] ┆ ["special │
│ , "NORWEGI ┆ "NN1"]     ┆ "SUBST"]   ┆         ┆ "]         ┆           ┆            ┆ ", "norwe │
│ AN",       ┆            ┆            ┆         ┆            ┆           ┆            ┆ gian",    │
│ "JACQ…     ┆            ┆            ┆         ┆            ┆           ┆            ┆ "jacq…    │
│ ["BRIEF",  ┆ ["AJ0",    ┆ ["ADJ",    ┆ written ┆ ["NONAC"]  ┆ ["BMB"]   ┆ ["I", "B"] ┆ ["brief", │
│ "British", ┆ "NN1"]     ┆ "SUBST"]   ┆         ┆            ┆           ┆            ┆ "british" │
│ "electron… ┆            ┆            ┆         ┆            ┆           ┆            ┆ , "electr │
│            ┆            ┆            ┆         ┆            ┆           ┆            ┆ on…       │
└────────────┴────────────┴────────────┴─────────┴────────────┴───────────┴────────────┴───────────┘

In [21]:
r.matches().group_by('token').len().sort(by='len', descending=True)

shape: (1_830_196, 2)
┌────────────────────────────┬──────┐
│ token                      ┆ len  │
│ ---                        ┆ ---  │
│ list[str]                  ┆ u32  │
╞════════════════════════════╪══════╡
│ ["Prime", "Minister"]      ┆ 7289 │
│ ["other", "hand"]          ┆ 5551 │
│ ["long", "time"]           ┆ 4169 │
│ ["great", "deal"]          ┆ 4019 │
│ ["other", "people"]        ┆ 3888 │
│ …                          ┆ …    │
│ ["hardened", "tone"]       ┆ 1    │
│ ["tremendous", "SPEELOSH"] ┆ 1    │
│ ["used", "tor"]            ┆ 1    │
│ ["ACOUSTIC", "Model"]      ┆ 1    │
│ ["other", "Sister"]        ┆ 1    │
└────────────────────────────┴──────┘

In [3]:
r = plc.search(c, '[pos="SUBST"]{3,}')

In [4]:
r.matches() \
    .with_columns(pl.col('token').list.join(' ')) \
    .group_by('token') \
    .len() \
    .sort(by='len', descending=True)

shape: (377_445, 2)
┌─────────────────────────────────┬──────┐
│ token                           ┆ len  │
│ ---                             ┆ ---  │
│ str                             ┆ u32  │
╞═════════════════════════════════╪══════╡
│ Pounds Date Award               ┆ 1811 │
│ Award Ref No                    ┆ 797  │
│ Research grant Award Ref No     ┆ 508  │
│ UN Security Council             ┆ 301  │
│ trade union movement            ┆ 223  │
│ …                               ┆ …    │
│ fighting platform speaker       ┆ 1    │
│ RESULTS Courage Leagues         ┆ 1    │
│ pre-adult training phase        ┆ 1    │
│ Northampton midfielder Stephen… ┆ 1    │
│ Brockham Green Village Society  ┆ 1    │
└─────────────────────────────────┴──────┘

In [78]:
%%time

left, kwic, right = [ ], [ ], [ ]
for s, e in r.matched_spans:
    s2 = max(s-5, 0)
    e2 = e + 5
    context = list(c['token'].slice(s2, e2-s2))
    left.append(context[:s-s2])
    kwic.append(context[s-s2:-5])
    right.append(context[-5:])
    #left.append(c['token'].slice(s-5, 5).implode()[0])
    #kwic.append(c['token'].slice(s, e-s).implode()[0])
    #right.append(c['token'].slice(e, 5).implode()[0])
concordance = pl.DataFrame({'left': left, 'kwic': kwic, 'right': right})

CPU times: user 4.86 s, sys: 157 ms, total: 5.02 s
Wall time: 5.02 s

In [79]:
concordance.with_columns(cs.all().list.join(' '))

shape: (519_054, 3)
┌────────────────────────────────┬────────────────────────────────┬────────────────────────────────┐
│ left                           ┆ kwic                           ┆ right                          │
│ ---                            ┆ ---                            ┆ ---                            │
│ str                            ┆ str                            ┆ str                            │
╞════════════════════════════════╪════════════════════════════════╪════════════════════════════════╡
│                                ┆ ACET AIDS CARE EDUCATION       ┆ AND TRAINING ANNUAL REVIEW     │
│                                ┆                                ┆ 199…                           │
│ 1 Director 's report 2–3       ┆ London Home Care               ┆ 4–5 ACET Scotland 6–7 ACET     │
│ more pressing demands on our   ┆ Home Care teams                ┆ . In the schools the           │
│ hospital . Please help !       ┆ SIR JOHN FORD KCMG MG CHAIRMAN ┆ OF TRUSTEES ACET 's mission    │
│ new HIV infections through a   ┆ schools education programme    ┆ . DIRECTOR 'S REPORT THE       │
│ …                              ┆ …                              ┆ …                              │
│ they can not offset their      ┆ child care costs               ┆ . Previously they could offset │
│ support children , to support  ┆ work place nurses              ┆ , to support the caring        │
│ <pause/> different aspects .   ┆ way people express emotion     ┆ is not simply a gender         │
│ T…                             ┆                                ┆                                │
│ , or who have pink             ┆ library book cards             ┆ for girls and blue library     │
│ cards for girls and blue       ┆ library book cards             ┆ for boys . This sort           │
└────────────────────────────────┴────────────────────────────────┴────────────────────────────────┘

In [84]:
concordance.explode('left')

shape: (2_595_266, 3)
┌──────────┬─────────────────────────────────┬─────────────────────────────────┐
│ left     ┆ kwic                            ┆ right                           │
│ ---      ┆ ---                             ┆ ---                             │
│ str      ┆ list[str]                       ┆ list[str]                       │
╞══════════╪═════════════════════════════════╪═════════════════════════════════╡
│ null     ┆ ["ACET", "AIDS", … "EDUCATION"… ┆ ["AND", "TRAINING", … "1990/91… │
│ 1        ┆ ["London", "Home", "Care"]      ┆ ["4–5", "ACET", … "ACET"]       │
│ Director ┆ ["London", "Home", "Care"]      ┆ ["4–5", "ACET", … "ACET"]       │
│ 's       ┆ ["London", "Home", "Care"]      ┆ ["4–5", "ACET", … "ACET"]       │
│ report   ┆ ["London", "Home", "Care"]      ┆ ["4–5", "ACET", … "ACET"]       │
│ …        ┆ …                               ┆ …                               │
│ cards    ┆ ["library", "book", "cards"]    ┆ ["for", "boys", … "sort"]       │
│ for      ┆ ["library", "book", "cards"]    ┆ ["for", "boys", … "sort"]       │
│ girls    ┆ ["library", "book", "cards"]    ┆ ["for", "boys", … "sort"]       │
│ and      ┆ ["library", "book", "cards"]    ┆ ["for", "boys", … "sort"]       │
│ blue     ┆ ["library", "book", "cards"]    ┆ ["for", "boys", … "sort"]       │
└──────────┴─────────────────────────────────┴─────────────────────────────────┘

In [53]:
s

13233