# Concordances

In [1]:

import polars as pl
import polars.selectors as cs

import polars_corpus as plc
import great_tables as gt

In [3]:
c = pl.read_parquet("../../data/amalgum.parquet")
c

shape: (3_850_429, 6)
┌──────────────┬─────┬──────────────┬──────────────┬─────────────────────────────┬───────────┐
│ token        ┆ pos ┆ lemma        ┆ sentence_tag ┆ file_id                     ┆ text_type │
│ ---          ┆ --- ┆ ---          ┆ ---          ┆ ---                         ┆ ---       │
│ str          ┆ str ┆ str          ┆ str          ┆ str                         ┆ str       │
╞══════════════╪═════╪══════════════╪══════════════╪═════════════════════════════╪═══════════╡
│ 1.           ┆ LS  ┆ 1.           ┆ B            ┆ AMALGUM_academic_acrylamide ┆ academic  │
│ Introduction ┆ NN  ┆ introduction ┆ I            ┆ AMALGUM_academic_acrylamide ┆ academic  │
│ Acrylamide   ┆ NNP ┆ Acrylamide   ┆ B            ┆ AMALGUM_academic_acrylamide ┆ academic  │
│ ,            ┆ ,   ┆ ,            ┆ I            ┆ AMALGUM_academic_acrylamide ┆ academic  │
│ a            ┆ DT  ┆ a            ┆ I            ┆ AMALGUM_academic_acrylamide ┆ academic  │
│ …            ┆ …   ┆ …            ┆ …            ┆ …                           ┆ …         │
│ out          ┆ IN  ┆ out          ┆ I            ┆ AMALGUM_whow_yacht          ┆ whow      │
│ of           ┆ IN  ┆ of           ┆ I            ┆ AMALGUM_whow_yacht          ┆ whow      │
│ the          ┆ DT  ┆ the          ┆ I            ┆ AMALGUM_whow_yacht          ┆ whow      │
│ harbor       ┆ NN  ┆ harbor       ┆ I            ┆ AMALGUM_whow_yacht          ┆ whow      │
│ .            ┆ .   ┆ .            ┆ I            ┆ AMALGUM_whow_yacht          ┆ whow      │
└──────────────┴─────┴──────────────┴──────────────┴─────────────────────────────┴───────────┘

In [9]:
m = plc.search(c, "light")
m

TypeError: search() got an unexpected keyword argument 'metadata'

In [13]:
m.view(window=5)

In [18]:
m.concordance(window=5, metadata='file_id').filter(pl.col('token_left_context').list.contains("benign"))

shape: (2, 4)
┌────────────────────────────────┬───────────┬──────────────────────┬──────────────────────────┐
│ token_left_context             ┆ token     ┆ token_right_context  ┆ file_id                  │
│ ---                            ┆ ---       ┆ ---                  ┆ ---                      │
│ list[str]                      ┆ list[str] ┆ list[str]            ┆ str                      │
╞════════════════════════════════╪═══════════╪══════════════════════╪══════════════════════════╡
│ ["a", "benign", … "unstained"] ┆ ["light"] ┆ [";", "the", … "on"] ┆ AMALGUM_fiction_brooding │
│ ["a", "benign", … "unstained"] ┆ ["light"] ┆ [";", "the", … "on"] ┆ AMALGUM_fiction_gloom    │
└────────────────────────────────┴───────────┴──────────────────────┴──────────────────────────┘

In [20]:
m = plc.search(c, "+ shall +")
m

SearchResults<'+ shall +'; 275 matches>

In [13]:
conc = m.concordance(pl.col('token').str.to_lowercase())
conc

shape: (275, 1)
┌──────────────────────────────┐
│ token                        │
│ ---                          │
│ list[str]                    │
╞══════════════════════════════╡
│ ["we", "shall", "use"]       │
│ ["reference", "shall", "be"] │
│ ["adder", "shall", "be"]     │
│ ["reference", "shall", "be"] │
│ ["we", "shall", "consider"]  │
│ …                            │
│ ["one", "shall", "lay"]      │
│ ["i", "shall", "not"]        │
│ ["they", "shall", "never"]   │
│ ["we", "shall", "."]         │
│ ["we", "shall", "keep"]      │
└──────────────────────────────┘

In [14]:
conc.group_by(pl.col('token')).len().sort(by='len', descending=True)

shape: (199, 2)
┌────────────────────────────┬─────┐
│ token                      ┆ len │
│ ---                        ┆ --- │
│ list[str]                  ┆ u32 │
╞════════════════════════════╪═════╡
│ ["i", "shall", "be"]       ┆ 18  │
│ ["i", "shall", "not"]      ┆ 11  │
│ ["we", "shall", "be"]      ┆ 8   │
│ ["i", "shall", "have"]     ┆ 6   │
│ ["what", "shall", "we"]    ┆ 4   │
│ …                          ┆ …   │
│ ["woman", "shall", "be"]   ┆ 1   │
│ ["then", "shall", "isaac"] ┆ 1   │
│ ["i", "shall", "pray"]     ┆ 1   │
│ ["i", "shall", "talk"]     ┆ 1   │
│ ["thou", "shall", "be"]    ┆ 1   │
└────────────────────────────┴─────┘

In [15]:
conc = m.concordance(pl.col('token').str.to_lowercase())
conc.group_by(pl.col('token').list.first()).len().sort(by='len', descending=True)

shape: (77, 2)
┌──────────────────┬─────┐
│ token            ┆ len │
│ ---              ┆ --- │
│ str              ┆ u32 │
╞══════════════════╪═════╡
│ i                ┆ 89  │
│ we               ┆ 47  │
│ you              ┆ 12  │
│ he               ┆ 10  │
│ what             ┆ 7   │
│ …                ┆ …   │
│ stake            ┆ 1   │
│ exams            ┆ 1   │
│ exhibition-rooms ┆ 1   │
│ heart            ┆ 1   │
│ strangers        ┆ 1   │
└──────────────────┴─────┘

In [16]:
conc.group_by(pl.col('token').list.last()).len().sort(by='len', descending=True)

shape: (120, 2)
┌───────────┬─────┐
│ token     ┆ len │
│ ---       ┆ --- │
│ str       ┆ u32 │
╞═══════════╪═════╡
│ be        ┆ 52  │
│ not       ┆ 24  │
│ have      ┆ 16  │
│ i         ┆ 16  │
│ never     ┆ 7   │
│ …         ┆ …   │
│ keep      ┆ 1   │
│ certainly ┆ 1   │
│ ;         ┆ 1   │
│ soon      ┆ 1   │
│ teem      ┆ 1   │
└───────────┴─────┘

In [21]:
conc = m.concordance(pl.col('pos'))
conc.group_by(pl.col('pos').list.first()).len().sort(by='len', descending=True)

shape: (20, 2)
┌─────┬─────┐
│ pos ┆ len │
│ --- ┆ --- │
│ str ┆ u32 │
╞═════╪═════╡
│ PRP ┆ 172 │
│ NN  ┆ 34  │
│ WP  ┆ 12  │
│ NNS ┆ 12  │
│ ,   ┆ 7   │
│ …   ┆ …   │
│ EX  ┆ 1   │
│ RBR ┆ 1   │
│ IN  ┆ 1   │
│ DT  ┆ 1   │
│ UH  ┆ 1   │
└─────┴─────┘

In [22]:
conc.group_by(pl.col('pos').list.last()).len().sort(by='len', descending=True)

shape: (10, 2)
┌──────┬─────┐
│ pos  ┆ len │
│ ---  ┆ --- │
│ str  ┆ u32 │
╞══════╪═════╡
│ VB   ┆ 187 │
│ RB   ┆ 48  │
│ PRP  ┆ 26  │
│ ,    ┆ 5   │
│ .    ┆ 3   │
│ PRP$ ┆ 2   │
│ IN   ┆ 1   │
│ VBG  ┆ 1   │
│ NNP  ┆ 1   │
│ :    ┆ 1   │
└──────┴─────┘

In [26]:
m.concordance("token", metadata='text_type') \
.group_by('text_type').len()

shape: (6, 2)
┌───────────┬─────┐
│ text_type ┆ len │
│ ---       ┆ --- │
│ str       ┆ u32 │
╞═══════════╪═════╡
│ whow      ┆ 4   │
│ academic  ┆ 11  │
│ interview ┆ 18  │
│ fiction   ┆ 221 │
│ news      ┆ 15  │
│ bio       ┆ 6   │
└───────────┴─────┘